### ISSUE TITLE
assumptions about github name

### ISSUE THREAD

**Issue by jadeqwang** [meteor/madewith2#1]
When Alice logged in, her name was set to null b/c she didn't have her real name filled out on github.

I haven't figured out how to get the github handle the package, but the correct answer would be to flexibly use whichever exists, favoring the real name when both exists.

**Comment by Slava** [comment]
Since we don't use GitHub anymore, should this be closed? Can you have the same bug with Meteor Dev Accounts?

**Comment by jadeqwang** [comment]
I agree.
